<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('css/style.css'))
            ->appendStylesheet($this->basePath('css/calendar.css'))
            ->appendStylesheet($this->basePath('fonts/flaticon/flaticon.css'))
            ->appendStylesheet($this->basePath('css/calendar.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        Uniques Software
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
            <?= $this->content ?>
        <div class="container">
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> by Laminas Project. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->appendFile($this->basePath('js/jquery-3.4.1.min.js'))
            ->appendFile($this->basePath('js/jquery-ui.min.js'))
            ->appendFile($this->basePath('js/popper.min.js'))
            ->appendFile($this->basePath('js/bootstrap.min.js'))
            ->appendFile($this->basePath('js/moment.min.js'))
            ->appendFile($this->basePath('js/calendar.min.js')) 
            ->appendFile($this->basePath('js/cal.js')) ?>
    </body>
</html>
